#google drive api
google:
  service_account_email: metalphoto@metalphoto.iam.gserviceaccount.com
  application_name: MetalPhoto
  folder_id: 1ICpxXF3PuHDVlHDJgwA81WgnpmTAUTXS
  service_account_key:

amazonProperties:
  endpointUrl: https://s3.eu-central-1.amazonaws.com
  accessKey: **********************
  secretKey: ******************************
  bucketName: metalbucket
